version: "2"
services:
  craft:
    image: craftcms/nginx:7.4
    ports:
      - 80:8080
    volumes:
      - ./app/.:/app/.
    links:
      - db
    environment:
      - VIRTUAL_HOST=127.0.0.1
      - VIRTUAL_PORT=80
      - ENVIRONMENT=dev
      - DB_SERVER=db
      - DB_USER=craft_user
      - DB_DATABASE=craft
      - DB_PASSWORD=password
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - VIRTUAL_HOST=127.0.0.1
      - MYSQL_DATABASE=craft
      - MYSQL_USER=craft_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
