defaultPlacement: end
enableVersioning: false
handle: Homepage
name: Homepage
propagationMethod: all
siteSettings:
  a757f90f-e80e-43d7-b9e4-7fe6411d9285:
    enabledByDefault: true
    hasUrls: true
    template: entries/pages/index
    uriFormat: __home__
type: single
